---
- name: Install
  become: yes
  apt: name=ufw state=latest

- name: Start
  ufw: state=enabled

- name: Allow IN 80/TCP  HTTP
  become: yes
  ufw: rule=allow direction=in port=80 proto=tcp

- name: Allow IN 443/TCP  HTTPS
  become: yes
  ufw: rule=allow direction=in port=443 proto=tcp

- name: Allow IN 22/TCP  SSH
  become: yes
  ufw: rule=allow direction=in port=22 proto=tcp

- name: Allow IN/OUT 53/UDP  DNS
  become: yes
  ufw: rule=allow port=53 proto=udp

- name: Allow OUT 11371/TCP  GPG server key
  become: yes
  ufw: rule=allow port=11371 direction=out proto=tcp
  notify: ufw reload


